### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by ghost** [noelsimbolon/mpv-config#1]
.

**Comment by noelsimbolon** [comment]
I noticed that you asked on how to install Anime4K before changing the title of this issue and your comment. For Anime4K installation instructions, please refer to their [documentation ](https://github.com/bloc97/Anime4K/blob/master/md/GLSL_Instructions_Windows.md) on how to install it on Windows. If you are on Linux, please refer to [this](https://github.com/bloc97/Anime4K/blob/master/md/GLSL_Instructions_Linux.md) documentation instead. The [Kokomins' guide](https://kokomins.wordpress.com/category/mpv/) might also be useful on how to set it up on your machine, there is a section that provides some information on Anime4K.

Although before installing it, I suggest that you understand that Anime4K is not and [upscaling algorithm](https://redvice.org/2019/on-anime4k/), rather a sharpening filter. Personally, it isn't for me. It makes anime look like oil paintings, but that's just my opinion 😉
