### ISSUE TITLE
Fullscreen does not persist through playlist

### ISSUE THREAD

**Issue by Amir1453** [noelsimbolon/mpv-config#3]
Hey, first of all nice configs, I really like it. 

OS: Arch Linux x86_64
Kernel: 6.3.9-arch1-1
mpv: mpv-1:0.35.1-6
Display Server: Wayland
DE: Hyprland

When playing the next video from the playlist, mpv toggles fullscreen once again. So for example if you  have 3 videos in the playlist when you press next video mpv would exit fullscreen and enter fullscreen again as you skip to the next video.

**Comment by noelsimbolon** [comment]
Hello, can you describe your issue more clearly? In my end, the fullscreen persists when navigating through the videos in the playlist. It doesn't resize the mpv window when playing the next video in the playlist. I'm testing in Linux with Wayland, although I'm using GNOME DE. If possible, can you provide a video recording showing the issue you're having? Thanks.

**Comment by Amir1453** [comment]
I did not edit any configs

scripts folder:
```
autoload.lua
cycle-commands.lua
cycle-profile.lua
mordenx.lua
playlistmanager.lua
seek-to.lua
thumbfast.lua
```
scripts-opt folder:
```
autoload.conf
osc.conf
thumbfast.conf
```
autoload.conf:
```
disabled=no
images=no
videos=yes
audio=yes
ignore_hidden=no
```
I ran a few tests:
When all the videos in the playlist are .mp4, the fullscreen toggle on/off does not occur when running mpv from the terminal and from ranger (file manager).

https://github.com/noelsimbolon/mpv-config/assets/63464110/9aa1c7a0-33f2-4968-93f9-796e35c7c5a7

When there is one video of different type (.webm), the video starts in fullscreen but toggles it off when switching to the mp4 video. There is no toggle between same types of videos. 

https://github.com/noelsimbolon/mpv-config/assets/63464110/efa61d33-5d04-41a8-b7b6-e6b6563eecad

I am guessing different mpv profiles load for different file formats so somehow mpv restarts and that toggles the fullscreen switch (even though mpv is still working).

**Comment by noelsimbolon** [comment]
After a bit of researching, it seems like this is a pretty common issue. This might be the default behavior of mpv. I guess it resizes the window according to the resolution of the video (or image), so it doesn't necessarily have something to do with the file format.

You can learn more about this issue on the following Reddit posts:
1. https://www.reddit.com/r/mpv/comments/ob22cd/any_way_to_stop_automatic_resizing_when_youre/
2. https://www.reddit.com/r/mpv/comments/rl62nt/prevent_window_resizing_following_video_resolution/
3. https://www.reddit.com/r/mpv/comments/yxs4tb/help_mpv_restores_from_full_screen_when_played/

I wrote a script, adapted from one of the Reddit posts above, that freezes the window geometry of mpv.
```lua
-- Toggle window geometry freezing.
-- Adapted from https://www.reddit.com/r/mpv/comments/ob22cd/any_way_to_stop_automatic_resizing_when_youre/

local toggle_freeze_key = "y"

local toggle_flag = true
local function toggle_freeze()
    if toggle_flag then
        local ww, wh = mp.get_osd_size()
        mp.set_property("geometry", string.format("%dx%d", ww, wh))
        mp.osd_message("Window size frozen.")
    else
        mp.set_property("geometry", "")
        mp.osd_message("Window size unfrozen.")
    end
    toggle_flag = not toggle_flag
end

mp.add_key_binding(toggle_freeze_key, 'toggle_freeze_key', toggle_freeze)
```

The default keybinding is <kbd>y</kbd>, but you can change it to anything you want by modifying the `toggle_freeze_key`. For example:
```lua
local toggle_freeze_key = "M"
```
I might add that script to this repo. Let me know if it suits your needs.

**Comment by Amir1453** [comment]
You are probably right that it is caused by resolutions rather than file types, I just tried it and the resizing issue persists even with all of the videos being .mp4 formats.

I tried the script, I can see the "Windows size frozen" indicator on the top left when I press "y", but nothing else happens. The windows still resize themselves when I change videos.

**Comment by noelsimbolon** [comment]
That's weird. Can you try the solutions provided in those Reddit posts above? See if one of them works.

**Comment by Amir1453** [comment]
Added the following to my `mpv.conf` from the second reddit link:

```sh
force-window
force-window-position
geometry=2560x1440
no-keepaspect-window
```

For some reason setting the geometry with the scripts or with flags did not work, I am guessing `force-window` and `force-window-position` must be enabled. Now mpv runs in my full screen resolution all the time, although there is still some weird behavior when switching videos. 

I suggest creating a seperate section with possible fixes in the README.md

**Comment by noelsimbolon** [comment]
Thanks for the input, I'll consider it.
