### ISSUE TITLE
Kaspersky doesn't like the discord tool

### ISSUE THREAD

**Issue by Chaython** [noelsimbolon/mpv-config#4]
User:
User type: Initiator
Application name: explorer.exe
Application path: C:\Windows
Component: File Anti-Virus
Result description: Backup copy created
Type: Trojan
Name: VHO:Trojan.Win32.Convagent.gen
Precision: Heuristic Analysis
Threat level: High
Object type: File
Object name: mpv-discord.exe
Object path: G:\Back_Up\Programs\Video\MPV\portable_config\bin
MD5 of an object: 60F795051F420C0F7D1CA952276A2056

Also when I delete the discord script and the exe mpv isn't starting with this config

**Comment by noelsimbolon** [comment]
I've decided to [remove](https://github.com/noelsimbolon/mpv-config/releases/tag/v1.0.5) the mpv discord script. It's unreliable and buggy at times.

**Comment by noelsimbolon** [comment]
You can find alternatives for the discord script on the [User Scripts page](https://github.com/mpv-player/mpv/wiki/User-Scripts) in the official mpv repository.
