### ISSUE TITLE
the modernx GUI is not showing up

### ISSUE THREAD

**Issue by TeusDev** [noelsimbolon/mpv-config#6]
![image](https://github.com/noelsimbolon/mpv-config/assets/45436136/8f7f5b5f-dede-4e7e-b0ab-84581612eb98)
mouse is moving but no HUD shows up, even using seek in keyboard arrows doesn't show anything, i set the level 3 in .conf for test purposes.

**Comment by noelsimbolon** [comment]
It seems like there is a problem with the script that is causing this and I'm unable to identify it. It has not been updated since [2 years ago](https://github.com/cyl0/ModernX/blob/main/modernx.lua). For now, you can try this recently updated [fork](https://github.com/zydezu/ModernX).
